# Generated by Django 4.0.6 on 2022-07-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ismni kiritish', max_length=5000, verbose_name='Ismni kiritish')),
                ('age', models.IntegerField(help_text='Yoshni kiritish', verbose_name='Yoshni kiritish')),
                ('technologies', models.TextField(help_text='Technolgies', verbose_name='Technologies')),
                ('profession', models.CharField(help_text='Kasbni kiritish', max_length=5000, verbose_name='Kasbni kiritish')),
                ('language', models.CharField(help_text='Tilni kiritish', max_length=5000, verbose_name='Tilni kiritish')),
                ('image', models.ImageField(help_text='Profil rasmi', upload_to='profile-images', verbose_name='Profil rasmi')),
                ('cv', models.FileField(help_text='cv', upload_to='cvs', verbose_name='CV')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.URLField(default='behzodasliddinov.uz')),
                ('instagram', models.URLField(default='behzodasliddinov.uz')),
                ('facebook', models.URLField(default='behzodasliddinov.uz')),
                ('github', models.URLField(default='behzodasliddinov.uz')),
                ('youtube', models.URLField(default='behzodasliddinov.uz')),
                ('linkedin', models.URLField(default='behzodasliddinov.uz')),
                ('phone', models.CharField(default='+998 99 116-04-34', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.IntegerField(default=1)),
            ],
        ),
    ]
